//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTUDDN_NguyenMinhDuc_21103100549_RestaurentOrder.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.HoaDonDatMons = new HashSet<HoaDonDatMon>();
        }
        [Key]
        public int MaMon { get; set; }
        [Required(ErrorMessage = "Tên món không được để trống.")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Tên món phải từ 5 đến 50 ký tự.")]
        public string TenMon { get; set; }
        [Required(ErrorMessage = "Loại món không được để trống.")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Loại món phải từ 5 đến 50 ký tự.")]
        public string LoaiMon { get; set; }
        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Đơn giá phải lớn hơn 0.")]
        public Nullable<decimal> DonGia { get; set; }
        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "Số lượng tồn phải lớn hơn hoặc bằng 0.")]
        public Nullable<int> SoLuongTon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonDatMon> HoaDonDatMons { get; set; }
    }
}
